[package]
name = "makelib"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]
closefds = "*"
serde_json = "*"
bincode = "1.2"
snap = "0.1"
serde = { version = "1.0", features = ["derive"] }
