[package]
name = "example"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[[bin]]
name="example"
path="src/example.rs"

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.widget]
path="../widget"

[dependencies.render]
path="../render"