[workspace]

members = [
    "makepad",
    "makepad/webgl",
    "tools/testhub",
    "tools/csvproc",
    "examples/text_example",
    "examples/quad_example",
    "examples/ui_example",
    "workspace"
]


[profile.release]
#lto = true
#opt-level = 'z'
#panic = "abort"
debug = true
#codegen-units = 1
