[package]
name = "makepad"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

#[profile.release]
#lto = true
#opt-level = 'z'
#panic = "abort"
#debug = false
#bgcodegen-units = 1

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.widget]
path="./widget"
default-features = false

[dependencies.editor]
path="./editor"
default-features = false

[dependencies.render]
path="./render"
default-features = false
features=["mtl"]

# other options are ["webgl"] and ["dx11"]. 
# linux/ogl is depricated for now 
# Webgl doesn't build with this cargo, use the one in webgl/
# but it can be needed to be set if you want RLS to show webGL errors
