[workspace]

members = [
    "makepad",
    "makepad/wasm",
    "tools/csvproc",
    "examples/text_example",
    "examples/ui_example",
    "workspace"
]

#[profile.release]
#lto = true
#opt-level = 'z'
#panic = "abort"
#debug = true
#codegen-units = 1
