[package]
name = "makepad_webgl"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[lib]
path = "../src/main.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.widget]
path="../../widget"

[dependencies.render]
path="../../render"

[dependencies.editor]
path="../editor"

[dependencies.terminal]
path="../terminal"
