[package]
name = "shader_ast_impl"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.13"
proc-macro-hack = "*"
proc-macro2 = "0.4.30"

[dependencies.syn]
version = "0.15"
features = ["full"]
