[package]
name = "makepad"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

#[profile.release]
#lto = true
#opt-level = 'z'
#panic = "abort"
#debug = false
#bgcodegen-units = 1

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.widget]
path="../widget"

[dependencies.editor]
path="./editor"

[dependencies.render]
path="../render"

[dependencies.terminal]
path="./terminal"

[dependencies.makelib]
path="./makelib"
