[package]
name = "csvproc"
version = "0.1.0"
edition = "2018"

[dependencies]
toml = "0.5" 
serde = { version = "1.0", features = ["derive"] }

[dependencies.wasmparser]
path = "../../makepad/hub/wasmparser"