[package]
name = "example_webgl"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[lib]
path = "../src/example.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
panic = "abort"
debug = false
codegen-units = 1

[dependencies]
rand = "*"
#syn = "*"

[dependencies.widget]
path="../widget"
default-features = false
features=["webgl"]

[dependencies.render]
path="../render"
default-features = false
features=["webgl"]
